### PR TITLE
Created schematic

### PR DESCRIPTION
**Pull request by JackToaster**
I designed for 5v servos. This will need to be changed if the servos we use run off of a different voltage.

### CODE REVIEW

**Comment by zainahm3d** [comment]
@JackToaster Couple things, most of the design looks great. 

First, lower the output capacitance on the 8074 regulator (look at the application in the schematic). Switching regulators don't like having a ton of output capacitance. It's best to increase the input capacitance (can put nearly unlimited capacitance here) and trust the regulator to manage the output. Otherwise you're essentially slowing down how fast the regulator can respond to changes on it's output. (section 2.1 - 2.4) https://www.ti.com/lit/an/slta055/slta055.pdf?ts=1637034978202&ref_url=https%253A%252F%252Fwww.google.com%252F

Next, we had issues in the past with browning out voltage rails when running servos. This is common with these servos because they pull power relentlessly, it's an issue in industry as well. The original plan 2 years back was to use a big junky amazon regulator to power the servos. I would recommend using a more powerful regulator for your 5v rail and completely decouple it from your other electronics. What you do not want is your microcontroller and CAN transceiver power supply to be affected by the servos browning out the 5V rail (and thus nuking your 3.3 rail).  So, you could have 3 regulators: 
12v -> 3.3V to power micro and other low power things
12v -> 5v beefy supply for servos 
12v -> 5v as a completely separate rail for any 5v things (if you even need it)
I would use a non integrated regulator for the servo 5V rail. 
One thing is for certain: the LTM8074 cannot handle multiple servos at once. It's rated output is only 1.2A and I've struggled to get more than 800mA out of them in practice. They're more meant for low power. 

edit: When laying this out make sure to keep your servo power rails away from CAN and any other sensitive lines, the current waveforms on servo power lines are gross.

Lemme know your thoughts on this, hobby servos are designed very cheaply and cause a lot of problems when they're not used on RC stuff with huge LiPo batteries 6 inches away.

**Comment by mf-zainahmed** [comment]
https://hitecrcd.com/products/servos/analog/sport-2/hs-645mg/product this spec page says 2.5A stall current, I bet it's common for servos to pull even more than that. Now multiply that 4x and you'll see the issue

on work account, plz ignore different username

**Comment by zainahm3d** [comment]
Looks good. I'll approve for now. 

2 recs: 
- Test out an external 5v regulator before ordering this board, make sure it can handle 4x servos with the load they are expected to see. 
- If it were me I would swap F1 for a PTC, I'm sure you know fuses are more meant to protect cabling then the electronics. A well sized PTC will protect your board and the cabling. Or, if you wanna be fancy there's this https://www.analog.com/en/products/ltc4365.html#product-overview .

**Review by zainahm3d — DISMISSED** [review]

**Comment by zainahm3d** [comment]
Oh also connect the STM32 EPAD to gnd
image

**Comment by JackToaster** [comment]
I've connected the EPad on the STM32 to gnd. Thanks for pointing that out!
I also replaced the fuse with a PTC. I went for one with a higher trip current (3A) since this board might be in fairly high temperature environments.

**Comment by zainahm3d** [comment]
Looks good, any reason you're using an adjustable regulator instead of a fixed 3.3V one? A fixed regulator is available in the same package and doesn't require the resistors.

**Comment by JackToaster** [comment]
> any reason you're using an adjustable regulator instead of a fixed 3.3V one? A fixed regulator is available in the same package and doesn't require the resistors.

I'm assuming you mean the LM1117 instead for a fixed 3.3V regulator in the same package. The reason chose the LM317 because it has a maximum input voltage of only 40V, whereas the LM1117 only has a max of 15V which could be exceeded even with the TVS diode.

**Comment by zainahm3d** [comment]
Oh I wasn't specifically pointing at a 1117, something like this would work though https://www.mouser.com/ProductDetail/Analog-Devices-Inc/LT1129IST-33TRPBF?qs=sGAEpiMZZMsKEdP9slC0YZC7jhNvTkVE58LGsJQTomI%3D

Realistically the input voltage isn't a huge deal on linear regulators (within reason) since you're nearly always constrained by package thermal performance because they're just fancy resistors. Pulling any real current out of one of these at >20v is never a fun time

**Comment by zainahm3d** [comment]
or this thing https://www.mouser.com/ProductDetail/Texas-Instruments/LM2936QMP-33-NOPB?qs=%2Fd%252BFzHvH4c03vbvEmi%2FHPg%3D%3D

**Comment by JackToaster** [comment]
I just replaced the adjustable regulator with a fixed 3.3v regulator. I chose the LT1129 you linked for the schematic, but there's [dozens](https://www.mouser.com/c/semiconductors/power-management-ics/voltage-regulators-voltage-controllers/ldo-voltage-regulators/?input%20voltage%20max=20%20V~~150%20V&output%20current=100%20mA~~2%20A&output%20voltage=3.15%20V%7C~3.2%20V%7C~3.3~~3.3%20V&package%20%2F%20case=SOT-223-3&rp=semiconductors%2Fpower-management-ics%2Fvoltage-regulators-voltage-controllers%2Fldo-voltage-regulators%7C~Output%20Voltage%7C~Input%20Voltage%20MAX%7C~Output%20Current) of equivalent parts with the same package that would work just as well.

**Comment by JackToaster** [comment]
I just replaced the adjustable regulator with a fixed 3.3v regulator. I chose the LT1129 you linked for the schematic, but there's [dozens](https://www.mouser.com/c/semiconductors/power-management-ics/voltage-regulators-voltage-controllers/ldo-voltage-regulators/?input%20voltage%20max=20%20V~~150%20V&output%20current=100%20mA~~2%20A&output%20voltage=3.15%20V%7C~3.2%20V%7C~3.3~~3.3%20V&package%20%2F%20case=SOT-223-3&rp=semiconductors%2Fpower-management-ics%2Fvoltage-regulators-voltage-controllers%2Fldo-voltage-regulators%7C~Output%20Voltage%7C~Input%20Voltage%20MAX%7C~Output%20Current) of equivalent parts with the same package that would work just as well.

**Comment by mf-zainahmed** [comment]
One more thing I just noticed, just going to share in case it matters, the regulator has built in RPP, so you can remove some more parts if you want (up to you of course) 
image

**Comment by JackToaster** [comment]
I think it would still be a good idea to keep the reverse polarity protection to protect the LEDs, since they're otherwise powered directly off of the 12V supply.

**Comment by zainahm3d** [comment]
I figured since the LEDs are diodes they should be able to take it - but it's never bad to have some extra redundancy. Looks great, excited to see the layout.

**Review by zainahm3d — APPROVED** [review]
💡

**Pull request merged**
